on: 
Â  push:
Â  Â  branches:
Â  Â  Â  - "staging"

name: ðŸš€ Deploy staging website on push
jobs:
Â  web-deploy:
Â  Â  name: ðŸŽ‰ Deploy staging
Â  Â  runs-on: ubuntu-latest
Â  Â  steps:
Â  Â  - name: ðŸšš Get latest code
Â  Â  Â  uses: actions/checkout@v3

Â  Â  - name: Check secrets
Â  Â  Â  run: |
Â  Â  Â  Â  echo ${{ secrets.ftp_username }} Â | sed 's/./& /g'
Â  Â  Â  Â  echo ${{ secrets.ftp_password }} Â | sed 's/./& /g'
Â  Â  - name: ðŸ”Ž Check IP
Â  Â  Â  run: curl https://api.ipify.org
Â  Â  
Â  Â  - name: ðŸ“‚ Sync files
Â  Â  Â  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
Â  Â  Â  with:
Â  Â  Â  Â  server: ftp.ilsito.altervista.org
Â  Â  Â  Â  username: ${{ secrets.ftp_username }}
Â  Â  Â  Â  password: ${{ secrets.ftp_password }}
Â  Â  Â  Â  local-dir: ./cryptop-html/
Â  Â  Â  Â  server-dir: /staging/
